# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project3
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'GoogleSignIn'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'lottie-ios'
pod 'AlamofireImage'
pod 'Alamofire'
pod 'Moya'
pod 'YelpAPI'
end
